wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
hidden_size:
  desc: null
  value: 32
gamma:
  desc: null
  value: 0.9
max_steps:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727250358
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 61
      4: 3.8.19
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
